name: Build documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          pip install gsw numpy Sphinx jupyter myst-parser sphix-rtd-theme
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build documentation
        run: |
          python -m jupyter nbconvert README.ipynb --execute --to rst --output README.rst
          sphinx-build docs _docs
